
package com.leasurecompagnon.appliweb.model.exception;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.5
 * 2019-03-07T16:08:15.325+01:00
 * Generated source version: 3.2.5
 */

@WebFault(name = "ajoutActiviteFault", targetNamespace = "http://www.example.org/CatalogueService/")
public class AjoutActiviteFault_Exception extends Exception {

    /**
	 * 
	 */
	private static final long serialVersionUID = -354789007147533704L;
	private AjoutActiviteFault ajoutActiviteFault;

    public AjoutActiviteFault_Exception() {
        super();
    }

    public AjoutActiviteFault_Exception(String message) {
        super(message);
    }

    public AjoutActiviteFault_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public AjoutActiviteFault_Exception(String message, AjoutActiviteFault ajoutActiviteFault) {
        super(message);
        this.ajoutActiviteFault = ajoutActiviteFault;
    }

    public AjoutActiviteFault_Exception(String message, AjoutActiviteFault ajoutActiviteFault, java.lang.Throwable cause) {
        super(message, cause);
        this.ajoutActiviteFault = ajoutActiviteFault;
    }

    public AjoutActiviteFault getFaultInfo() {
        return this.ajoutActiviteFault;
    }
}
