
package com.leasurecompagnon.appliweb.model.exception;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.5
 * 2019-03-07T16:08:17.316+01:00
 * Generated source version: 3.2.5
 */

@WebFault(name = "authentifierUtilisateurFault", targetNamespace = "http://www.example.org/UtilisateurService/")
public class AuthentifierUtilisateurFault_Exception extends Exception {

    /**
	 * 
	 */
	private static final long serialVersionUID = 5687519738059709581L;
	private AuthentifierUtilisateurFault authentifierUtilisateurFault;

    public AuthentifierUtilisateurFault_Exception() {
        super();
    }

    public AuthentifierUtilisateurFault_Exception(String message) {
        super(message);
    }

    public AuthentifierUtilisateurFault_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public AuthentifierUtilisateurFault_Exception(String message, AuthentifierUtilisateurFault authentifierUtilisateurFault) {
        super(message);
        this.authentifierUtilisateurFault = authentifierUtilisateurFault;
    }

    public AuthentifierUtilisateurFault_Exception(String message, AuthentifierUtilisateurFault authentifierUtilisateurFault, java.lang.Throwable cause) {
        super(message, cause);
        this.authentifierUtilisateurFault = authentifierUtilisateurFault;
    }

    public AuthentifierUtilisateurFault getFaultInfo() {
        return this.authentifierUtilisateurFault;
    }
}
