
package com.leasurecompagnon.appliweb.model.exception;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.5
 * 2019-03-27T13:49:11.055+01:00
 * Generated source version: 3.2.5
 */

@WebFault(name = "deleteAvisFault", targetNamespace = "http://www.example.org/CatalogueService/")
public class DeleteAvisFault_Exception extends Exception {

    /**
	 * 
	 */
	private static final long serialVersionUID = 3145771002162143984L;
	private DeleteAvisFault deleteAvisFault;

    public DeleteAvisFault_Exception() {
        super();
    }

    public DeleteAvisFault_Exception(String message) {
        super(message);
    }

    public DeleteAvisFault_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public DeleteAvisFault_Exception(String message, DeleteAvisFault deleteAvisFault) {
        super(message);
        this.deleteAvisFault = deleteAvisFault;
    }

    public DeleteAvisFault_Exception(String message, DeleteAvisFault deleteAvisFault, java.lang.Throwable cause) {
        super(message, cause);
        this.deleteAvisFault = deleteAvisFault;
    }

    public DeleteAvisFault getFaultInfo() {
        return this.deleteAvisFault;
    }
}
