
package com.leasurecompagnon.appliweb.model.exception;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.5
 * 2019-03-07T16:08:16.377+01:00
 * Generated source version: 3.2.5
 */

@WebFault(name = "envoiFormulaireContactFault", targetNamespace = "http://www.example.org/FormulaireContactService/")
public class EnvoiFormulaireContactFault_Exception extends Exception {

    /**
	 * 
	 */
	private static final long serialVersionUID = -1628418233899380787L;
	private EnvoiFormulaireContactFault envoiFormulaireContactFault;

    public EnvoiFormulaireContactFault_Exception() {
        super();
    }

    public EnvoiFormulaireContactFault_Exception(String message) {
        super(message);
    }

    public EnvoiFormulaireContactFault_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public EnvoiFormulaireContactFault_Exception(String message, EnvoiFormulaireContactFault envoiFormulaireContactFault) {
        super(message);
        this.envoiFormulaireContactFault = envoiFormulaireContactFault;
    }

    public EnvoiFormulaireContactFault_Exception(String message, EnvoiFormulaireContactFault envoiFormulaireContactFault, java.lang.Throwable cause) {
        super(message, cause);
        this.envoiFormulaireContactFault = envoiFormulaireContactFault;
    }

    public EnvoiFormulaireContactFault getFaultInfo() {
        return this.envoiFormulaireContactFault;
    }
}
