
package com.leasurecompagnon.appliweb.model.exception;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.5
 * 2019-03-07T16:08:15.336+01:00
 * Generated source version: 3.2.5
 */

@WebFault(name = "getActiviteNomFault", targetNamespace = "http://www.example.org/CatalogueService/")
public class GetActiviteNomFault_Exception extends Exception {

    /**
	 * 
	 */
	private static final long serialVersionUID = -5298722563097069226L;
	private GetActiviteNomFault getActiviteNomFault;

    public GetActiviteNomFault_Exception() {
        super();
    }

    public GetActiviteNomFault_Exception(String message) {
        super(message);
    }

    public GetActiviteNomFault_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public GetActiviteNomFault_Exception(String message, GetActiviteNomFault getActiviteNomFault) {
        super(message);
        this.getActiviteNomFault = getActiviteNomFault;
    }

    public GetActiviteNomFault_Exception(String message, GetActiviteNomFault getActiviteNomFault, java.lang.Throwable cause) {
        super(message, cause);
        this.getActiviteNomFault = getActiviteNomFault;
    }

    public GetActiviteNomFault getFaultInfo() {
        return this.getActiviteNomFault;
    }
}
