
package com.leasurecompagnon.appliweb.model.exception;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.5
 * 2019-03-07T16:08:15.487+01:00
 * Generated source version: 3.2.5
 */

@WebFault(name = "getActiviteFault", targetNamespace = "http://www.example.org/CatalogueService/")
public class GetActiviteFault_Exception extends Exception {

    /**
	 * 
	 */
	private static final long serialVersionUID = -4780169822246026915L;
	private GetActiviteFault getActiviteFault;

    public GetActiviteFault_Exception() {
        super();
    }

    public GetActiviteFault_Exception(String message) {
        super(message);
    }

    public GetActiviteFault_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public GetActiviteFault_Exception(String message, GetActiviteFault getActiviteFault) {
        super(message);
        this.getActiviteFault = getActiviteFault;
    }

    public GetActiviteFault_Exception(String message, GetActiviteFault getActiviteFault, java.lang.Throwable cause) {
        super(message, cause);
        this.getActiviteFault = getActiviteFault;
    }

    public GetActiviteFault getFaultInfo() {
        return this.getActiviteFault;
    }
}
