
package com.leasurecompagnon.appliweb.model.exception;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.5
 * 2019-03-07T16:08:15.504+01:00
 * Generated source version: 3.2.5
 */

@WebFault(name = "getListDureeFault", targetNamespace = "http://www.example.org/CatalogueService/")
public class GetListDureeFault_Exception extends Exception {

    /**
	 * 
	 */
	private static final long serialVersionUID = 4889515451202066182L;
	private GetListDureeFault getListDureeFault;

    public GetListDureeFault_Exception() {
        super();
    }

    public GetListDureeFault_Exception(String message) {
        super(message);
    }

    public GetListDureeFault_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public GetListDureeFault_Exception(String message, GetListDureeFault getListDureeFault) {
        super(message);
        this.getListDureeFault = getListDureeFault;
    }

    public GetListDureeFault_Exception(String message,GetListDureeFault getListDureeFault, java.lang.Throwable cause) {
        super(message, cause);
        this.getListDureeFault = getListDureeFault;
    }

    public GetListDureeFault getFaultInfo() {
        return this.getListDureeFault;
    }
}
