
package com.leasurecompagnon.appliweb.model.exception;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.5
 * 2019-03-07T16:08:15.652+01:00
 * Generated source version: 3.2.5
 */

@WebFault(name = "getListTypeActiviteFault", targetNamespace = "http://www.example.org/CatalogueService/")
public class GetListTypeActiviteFault_Exception extends Exception {

    /**
	 * 
	 */
	private static final long serialVersionUID = 4259960536594796220L;
	private GetListTypeActiviteFault getListTypeActiviteFault;

    public GetListTypeActiviteFault_Exception() {
        super();
    }

    public GetListTypeActiviteFault_Exception(String message) {
        super(message);
    }

    public GetListTypeActiviteFault_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public GetListTypeActiviteFault_Exception(String message, GetListTypeActiviteFault getListTypeActiviteFault) {
        super(message);
        this.getListTypeActiviteFault = getListTypeActiviteFault;
    }

    public GetListTypeActiviteFault_Exception(String message, GetListTypeActiviteFault getListTypeActiviteFault, java.lang.Throwable cause) {
        super(message, cause);
        this.getListTypeActiviteFault = getListTypeActiviteFault;
    }

    public GetListTypeActiviteFault getFaultInfo() {
        return this.getListTypeActiviteFault;
    }
}
