
package com.leasurecompagnon.appliweb.model.exception;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.5
 * 2019-03-07T16:08:15.588+01:00
 * Generated source version: 3.2.5
 */

@WebFault(name = "getListRegionFault", targetNamespace = "http://www.example.org/CatalogueService/")
public class GetListRegionFault_Exception extends Exception {

    /**
	 * 
	 */
	private static final long serialVersionUID = 5724513431932852984L;
	private GetListRegionFault getListRegionFault;

    public GetListRegionFault_Exception() {
        super();
    }

    public GetListRegionFault_Exception(String message) {
        super(message);
    }

    public GetListRegionFault_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public GetListRegionFault_Exception(String message, GetListRegionFault getListRegionFault) {
        super(message);
        this.getListRegionFault = getListRegionFault;
    }

    public GetListRegionFault_Exception(String message, GetListRegionFault getListRegionFault, java.lang.Throwable cause) {
        super(message, cause);
        this.getListRegionFault = getListRegionFault;
    }

    public GetListRegionFault getFaultInfo() {
        return this.getListRegionFault;
    }
}
