
package com.leasurecompagnon.appliweb.model.exception;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.5
 * 2019-03-07T16:08:15.309+01:00
 * Generated source version: 3.2.5
 */

@WebFault(name = "getListActiviteFault", targetNamespace = "http://www.example.org/CatalogueService/")
public class GetListActiviteFault_Exception extends Exception {

    /**
	 * 
	 */
	private static final long serialVersionUID = -3236333303645870309L;
	private GetListActiviteFault getListActiviteFault;

    public GetListActiviteFault_Exception() {
        super();
    }

    public GetListActiviteFault_Exception(String message) {
        super(message);
    }

    public GetListActiviteFault_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public GetListActiviteFault_Exception(String message, GetListActiviteFault getListActiviteFault) {
        super(message);
        this.getListActiviteFault = getListActiviteFault;
    }

    public GetListActiviteFault_Exception(String message, GetListActiviteFault getListActiviteFault, java.lang.Throwable cause) {
        super(message, cause);
        this.getListActiviteFault = getListActiviteFault;
    }

    public GetListActiviteFault getFaultInfo() {
        return this.getListActiviteFault;
    }
}
