
package com.leasurecompagnon.appliweb.model.exception;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.5
 * 2019-03-07T16:08:15.554+01:00
 * Generated source version: 3.2.5
 */

@WebFault(name = "getListActiviteVilleFault", targetNamespace = "http://www.example.org/CatalogueService/")
public class GetListActiviteVilleFault_Exception extends Exception {

    /**
	 * 
	 */
	private static final long serialVersionUID = -8370421081001941235L;
	private GetListActiviteVilleFault getListActiviteVilleFault;

    public GetListActiviteVilleFault_Exception() {
        super();
    }

    public GetListActiviteVilleFault_Exception(String message) {
        super(message);
    }

    public GetListActiviteVilleFault_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public GetListActiviteVilleFault_Exception(String message, GetListActiviteVilleFault getListActiviteVilleFault) {
        super(message);
        this.getListActiviteVilleFault = getListActiviteVilleFault;
    }

    public GetListActiviteVilleFault_Exception(String message, GetListActiviteVilleFault getListActiviteVilleFault, java.lang.Throwable cause) {
        super(message, cause);
        this.getListActiviteVilleFault = getListActiviteVilleFault;
    }

    public GetListActiviteVilleFault getFaultInfo() {
        return this.getListActiviteVilleFault;
    }
}
