
package com.leasurecompagnon.appliweb.model.exception;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.5
 * 2019-03-07T16:08:15.690+01:00
 * Generated source version: 3.2.5
 */

@WebFault(name = "getListVilleRechercheFault", targetNamespace = "http://www.example.org/CatalogueService/")
public class GetListVilleRechercheFault_Exception extends Exception {

    /**
	 * 
	 */
	private static final long serialVersionUID = -3668836827430652105L;
	private GetListVilleRechercheFault getListVilleRechercheFault;

    public GetListVilleRechercheFault_Exception() {
        super();
    }

    public GetListVilleRechercheFault_Exception(String message) {
        super(message);
    }

    public GetListVilleRechercheFault_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public GetListVilleRechercheFault_Exception(String message, GetListVilleRechercheFault getListVilleRechercheFault) {
        super(message);
        this.getListVilleRechercheFault = getListVilleRechercheFault;
    }

    public GetListVilleRechercheFault_Exception(String message, GetListVilleRechercheFault getListVilleRechercheFault, java.lang.Throwable cause) {
        super(message, cause);
        this.getListVilleRechercheFault = getListVilleRechercheFault;
    }

    public GetListVilleRechercheFault getFaultInfo() {
        return this.getListVilleRechercheFault;
    }
}
