
package com.leasurecompagnon.appliweb.model.exception;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.5
 * 2019-03-07T16:08:15.398+01:00
 * Generated source version: 3.2.5
 */

@WebFault(name = "getListDepartementFault", targetNamespace = "http://www.example.org/CatalogueService/")
public class GetListDepartementFault_Exception extends Exception {

    /**
	 * 
	 */
	private static final long serialVersionUID = -357819969934290071L;
	private GetListDepartementFault getListDepartementFault;

    public GetListDepartementFault_Exception() {
        super();
    }

    public GetListDepartementFault_Exception(String message) {
        super(message);
    }

    public GetListDepartementFault_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public GetListDepartementFault_Exception(String message, GetListDepartementFault getListDepartementFault) {
        super(message);
        this.getListDepartementFault = getListDepartementFault;
    }

    public GetListDepartementFault_Exception(String message, GetListDepartementFault getListDepartementFault, java.lang.Throwable cause) {
        super(message, cause);
        this.getListDepartementFault = getListDepartementFault;
    }

    public GetListDepartementFault getFaultInfo() {
        return this.getListDepartementFault;
    }
}
