
package com.leasurecompagnon.appliweb.model.exception;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.5
 * 2019-03-07T16:08:15.344+01:00
 * Generated source version: 3.2.5
 */

@WebFault(name = "getListSaisonFault", targetNamespace = "http://www.example.org/CatalogueService/")
public class GetListSaisonFault_Exception extends Exception {

    /**
	 * 
	 */
	private static final long serialVersionUID = -6480811894002297654L;
	private GetListSaisonFault getListSaisonFault;

    public GetListSaisonFault_Exception() {
        super();
    }

    public GetListSaisonFault_Exception(String message) {
        super(message);
    }

    public GetListSaisonFault_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public GetListSaisonFault_Exception(String message, GetListSaisonFault getListSaisonFault) {
        super(message);
        this.getListSaisonFault = getListSaisonFault;
    }

    public GetListSaisonFault_Exception(String message, GetListSaisonFault getListSaisonFault, java.lang.Throwable cause) {
        super(message, cause);
        this.getListSaisonFault = getListSaisonFault;
    }

    public GetListSaisonFault getFaultInfo() {
        return this.getListSaisonFault;
    }
}
