
package com.leasurecompagnon.appliweb.model.exception;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.5
 * 2019-03-07T16:08:15.297+01:00
 * Generated source version: 3.2.5
 */

@WebFault(name = "getListPaysFault", targetNamespace = "http://www.example.org/CatalogueService/")
public class GetListPaysFault_Exception extends Exception {

    /**
	 * 
	 */
	private static final long serialVersionUID = -8791834590434990726L;
	private GetListPaysFault getListPaysFault;

    public GetListPaysFault_Exception() {
        super();
    }

    public GetListPaysFault_Exception(String message) {
        super(message);
    }

    public GetListPaysFault_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public GetListPaysFault_Exception(String message, GetListPaysFault getListPaysFault) {
        super(message);
        this.getListPaysFault = getListPaysFault;
    }

    public GetListPaysFault_Exception(String message, GetListPaysFault getListPaysFault, java.lang.Throwable cause) {
        super(message, cause);
        this.getListPaysFault = getListPaysFault;
    }

    public GetListPaysFault getFaultInfo() {
        return this.getListPaysFault;
    }
}
