
package com.leasurecompagnon.appliweb.model.exception;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.5
 * 2019-03-07T16:08:17.310+01:00
 * Generated source version: 3.2.5
 */

@WebFault(name = "getUtilisateurFault", targetNamespace = "http://www.example.org/UtilisateurService/")
public class GetUtilisateurFault_Exception extends Exception {

    /**
	 * 
	 */
	private static final long serialVersionUID = 5834315517582622578L;
	private GetUtilisateurFault getUtilisateurFault;

    public GetUtilisateurFault_Exception() {
        super();
    }

    public GetUtilisateurFault_Exception(String message) {
        super(message);
    }

    public GetUtilisateurFault_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public GetUtilisateurFault_Exception(String message, GetUtilisateurFault getUtilisateurFault) {
        super(message);
        this.getUtilisateurFault = getUtilisateurFault;
    }

    public GetUtilisateurFault_Exception(String message, GetUtilisateurFault getUtilisateurFault, java.lang.Throwable cause) {
        super(message, cause);
        this.getUtilisateurFault = getUtilisateurFault;
    }

    public GetUtilisateurFault getFaultInfo() {
        return this.getUtilisateurFault;
    }
}
