
package com.leasurecompagnon.appliweb.model.exception;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.5
 * 2019-03-07T16:08:15.451+01:00
 * Generated source version: 3.2.5
 */

@WebFault(name = "getVilleFault", targetNamespace = "http://www.example.org/CatalogueService/")
public class GetVilleFault_Exception extends Exception {

    /**
	 * 
	 */
	private static final long serialVersionUID = 2763076827366249641L;
	private GetVilleFault getVilleFault;

    public GetVilleFault_Exception() {
        super();
    }

    public GetVilleFault_Exception(String message) {
        super(message);
    }

    public GetVilleFault_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public GetVilleFault_Exception(String message, GetVilleFault getVilleFault) {
        super(message);
        this.getVilleFault = getVilleFault;
    }

    public GetVilleFault_Exception(String message, GetVilleFault getVilleFault, java.lang.Throwable cause) {
        super(message, cause);
        this.getVilleFault = getVilleFault;
    }

    public GetVilleFault getFaultInfo() {
        return this.getVilleFault;
    }
}
