
package com.leasurecompagnon.appliweb.model.exception;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.5
 * 2019-03-27T13:49:10.873+01:00
 * Generated source version: 3.2.5
 */

@WebFault(name = "updateStatutAvisFault", targetNamespace = "http://www.example.org/CatalogueService/")
public class UpdateStatutAvisFault_Exception extends Exception {

    /**
	 * 
	 */
	private static final long serialVersionUID = 6154561835822315356L;
	private UpdateStatutAvisFault updateStatutAvisFault;

    public UpdateStatutAvisFault_Exception() {
        super();
    }

    public UpdateStatutAvisFault_Exception(String message) {
        super(message);
    }

    public UpdateStatutAvisFault_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public UpdateStatutAvisFault_Exception(String message, UpdateStatutAvisFault updateStatutAvisFault) {
        super(message);
        this.updateStatutAvisFault = updateStatutAvisFault;
    }

    public UpdateStatutAvisFault_Exception(String message, UpdateStatutAvisFault updateStatutAvisFault, java.lang.Throwable cause) {
        super(message, cause);
        this.updateStatutAvisFault = updateStatutAvisFault;
    }

    public UpdateStatutAvisFault getFaultInfo() {
        return this.updateStatutAvisFault;
    }
}
