
package com.leasurecompagnon.appliweb.model.exception;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.5
 * 2019-03-07T16:08:17.347+01:00
 * Generated source version: 3.2.5
 */

@WebFault(name = "updateCoordUtilisateurFault", targetNamespace = "http://www.example.org/UtilisateurService/")
public class UpdateCoordUtilisateurFault_Exception extends Exception {

    /**
	 * 
	 */
	private static final long serialVersionUID = 6551109385298002208L;
	private UpdateCoordUtilisateurFault updateCoordUtilisateurFault;

    public UpdateCoordUtilisateurFault_Exception() {
        super();
    }

    public UpdateCoordUtilisateurFault_Exception(String message) {
        super(message);
    }

    public UpdateCoordUtilisateurFault_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public UpdateCoordUtilisateurFault_Exception(String message, UpdateCoordUtilisateurFault updateCoordUtilisateurFault) {
        super(message);
        this.updateCoordUtilisateurFault = updateCoordUtilisateurFault;
    }

    public UpdateCoordUtilisateurFault_Exception(String message, UpdateCoordUtilisateurFault updateCoordUtilisateurFault, java.lang.Throwable cause) {
        super(message, cause);
        this.updateCoordUtilisateurFault = updateCoordUtilisateurFault;
    }

    public UpdateCoordUtilisateurFault getFaultInfo() {
        return this.updateCoordUtilisateurFault;
    }
}
